version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 16
      - echo Installing source NPM...
      - npm install -g @angular/cli
      - echo Installing project NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo "Printing the content of environment.ts and environment.prod.ts files..."
      - cat src/environments/environment.ts
      - cat src/environments/environment.prod.ts
  build:
    commands:
      - echo Building the Angular app...
      - ng build --configuration production
  post_build:
    commands:
      - echo Syncing built app to S3...
      - aws s3 sync dist/resume-frontend s3://resume-frontend/ --delete