version: 0.2

phases:
  install:
    commands:
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - . ~/.nvm/nvm.sh
      - nvm install 16
      - nvm alias default 16
      - echo Checking node and npm versions
      - which node
      - node --version
      - npm -v
      - echo Installing source NPM...
      - npm install -g @angular/cli@15.2.5
      - echo Installing project NPM dependencies...
      - npm install
  build:
    commands:
      - echo Building the Angular app...
      - ng build --configuration production
  post_build:
    commands:
      - echo Syncing built app to S3...
      - aws s3 sync dist/resume-frontend s3://resume-frontend --delete
